version: '3.7'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  backend:
    build: ./backend
    restart: always
    volumes:
      - ./backend:/app
      - static:/app/staticfiles
      - media:/app/media
    ports:
      - '8000:8000'
    environment:
      - DB_NAME=${POSTGRES_DB}
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DEBUG=${DEBUG}
      - HOST=${HOST}
    depends_on:
      - db

  frontend:
    build: ./frontend
    restart: always
    volumes:
      - ./frontend:/app
    ports:
      - '3000:3000'
    depends_on:
      - backend
    command: >
      sh -c "npm install && npm run dev"

volumes:
  static:
  media: