# Generated by Django 5.0.4 on 2024-04-18 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Properties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('bedrooms', models.PositiveIntegerField(verbose_name='Quartos')),
                ('bathrooms', models.PositiveIntegerField(verbose_name='Banheiros')),
                ('parking', models.PositiveIntegerField(verbose_name='Vagas de Garagem')),
                ('area', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Área')),
                ('photo', models.ImageField(upload_to='properties', verbose_name='Foto')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço')),
            ],
            options={
                'verbose_name': 'Propriedade',
                'verbose_name_plural': 'Propriedades',
                'ordering': ('title',),
            },
        ),
    ]
