# Generated by Django 5.0.4 on 2024-04-30 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='fotos')),
            ],
            options={
                'verbose_name': 'Foto',
                'verbose_name_plural': 'Fotos',
            },
        ),
        migrations.RemoveField(
            model_name='properties',
            name='photo',
        ),
        migrations.AddField(
            model_name='properties',
            name='photos',
            field=models.ManyToManyField(blank=True, to='properties.foto'),
        ),
    ]
