# Generated by Django 5.0.4 on 2024-05-05 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_foto_remove_properties_photo_properties_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto',
            name='foto',
            field=models.BinaryField(editable=True, null=True),
        ),
    ]
