# Generated by Django 5.0.4 on 2024-05-05 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_alter_foto_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto',
            name='foto',
            field=models.ImageField(default=1, upload_to='fotos'),
            preserve_default=False,
        ),
    ]
