# Generated by Django 5.0.4 on 2024-05-07 04:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_alter_foto_foto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='properties',
            options={'ordering': ('created_at',), 'verbose_name': 'Propriedade', 'verbose_name_plural': 'Propriedades'},
        ),
        migrations.AddField(
            model_name='foto',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='foto',
            name='foto',
            field=models.ImageField(upload_to='fotos', verbose_name='Foto'),
        ),
    ]
