# Generated by Django 5.0.4 on 2024-05-07 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_alter_properties_options_foto_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foto',
            options={'ordering': ('created_at',), 'verbose_name': 'Foto', 'verbose_name_plural': 'Fotos'},
        ),
        migrations.AddField(
            model_name='properties',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Localização'),
        ),
    ]
