# Generated by Django 5.0.4 on 2024-05-07 04:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_alter_foto_options_properties_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
