# Generated by Django 5.0.4 on 2024-05-07 04:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_alter_foto_options_remove_foto_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='foto',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
