# Generated by Django 5.0.4 on 2024-05-07 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0010_foto_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foto',
            options={'ordering': ('created_at',), 'verbose_name': 'Foto', 'verbose_name_plural': 'Fotos'},
        ),
    ]
