# Generated by Django 5.0.4 on 2024-05-08 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0012_alter_foto_options_foto_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='properties',
            name='location',
        ),
        migrations.AddField(
            model_name='properties',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='properties',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Estado'),
        ),
    ]
